name: Gradle - Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Github Packages Deployment
    steps:
    - uses: actions/checkout@v4

    - name: Extract version from build.gradle.kts
      id: extract_version
      run: |
        VERSION=$(grep 'version *= *"' build.gradle.kts | sed -E 's/.*version *= *"([^"]+)".*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew build -DskipNative --no-daemon

    - name: Publish to GitHub Packages
      run: ./gradlew publish -DskipNative --no-daemon
      env:
        USERNAME: metinkale38
        TOKEN: ${{ secrets.ACCESS_TOKEN }}