name: Docker - Build and Deploy Server (native)

#on:
#  push:
#    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Github Packages Deployment
    steps:
    - uses: actions/checkout@v4

    - name: Extract version from build.gradle.kts
      id: extract_version
      run: |
        VERSION=$(grep 'version *= *"' build.gradle.kts | sed -E 's/.*version *= *"([^"]+)".*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile-server-native --tag ghcr.io/metinkale38/open-prayer-times:${VERSION}-native

    - uses: actions/checkout@v3
    - name: Build and push the image
      run : |
        docker login --username metinkale38 --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
        docker push ghcr.io/metinkale38/open-prayer-times:${VERSION}-native

    - name: Build the Docker image
      run: docker build . --file Dockerfile-server --tag ghcr.io/metinkale38/open-prayer-times:${VERSION}

    - uses: actions/checkout@v3
    - name: Build and push the image
      run : |
        docker login --username metinkale38 --password ${{ secrets.ACCESS_TOKEN }} ghcr.io
        docker push ghcr.io/metinkale38/open-prayer-times:${VERSION}